version: 2.1

orbs:
  win: circleci/windows@5.0.0
  macos: circleci/macos@2.5.2

jobs:
  windows_x86_64_compile:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: choco install -y mingw nsis
      - run: curl.exe --output rustup-init.exe --url https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe
      - run: ./rustup-init.exe -vy
      - run: rustup toolchain install stable-x86_64-pc-windows-msvc
      - run: rustup default stable-x86_64-pc-windows-msvc
      - run: cargo build --release
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  windows_x86_64_build:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: choco install -y mingw nsis
      - run: curl.exe --output rustup-init.exe --url https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe
      - run: ./rustup-init.exe -vy
      - run: rustup toolchain install stable-x86_64-pc-windows-msvc
      - run: rustup default stable-x86_64-pc-windows-msvc
      - run: cargo build --release
      - run: $env:Path += "C:\Program Files (x86)\NSIS\Bin"; makensis ./installer/windows/agent-installer.nsi
      - run:
          name: push to jfrog
          command: |
            $env:version = if ($env:CIRCLE_TAG) { $env:CIRCLE_TAG } else { if ($env:CIRCLE_BRANCH -eq "main") { "latest" } else { "prerelease" } }
            curl.exe -u samuel.hassine@filigran.io:$env:JFROG_TOKEN -T ./target/release/openbas-agent.exe "https://filigran.jfrog.io/artifactory/openbas-agent/windows/x86_64/openbas-agent-$env:version.exe"
            curl.exe -u samuel.hassine@filigran.io:$env:JFROG_TOKEN -T ./installer/windows/agent-installer.exe "https://filigran.jfrog.io/artifactory/openbas-agent/windows/x86_64/openbas-agent-installer-$env:version.exe"
            curl.exe -u samuel.hassine@filigran.io:$env:JFROG_TOKEN -T ./installer/windows/agent-installer.ps1 "https://filigran.jfrog.io/artifactory/openbas-agent/windows/openbas-agent-installer-$env:version.ps1"
            curl.exe -u samuel.hassine@filigran.io:$env:JFROG_TOKEN -T ./installer/windows/agent-upgrade.ps1 "https://filigran.jfrog.io/artifactory/openbas-agent/windows/openbas-agent-upgrade-$env:version.ps1"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  linux_x86_64_compile:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install curl musl-tools
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; rustup target add x86_64-unknown-linux-musl
      - run: . "$HOME/.cargo/env"; cargo build --target=x86_64-unknown-linux-musl --release
      - run: strip ./target/x86_64-unknown-linux-musl/release/openbas-agent
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  linux_x86_64_build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install curl musl-tools
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; rustup target add x86_64-unknown-linux-musl
      - run: . "$HOME/.cargo/env"; cargo build --target=x86_64-unknown-linux-musl --release
      - run: strip ./target/x86_64-unknown-linux-musl/release/openbas-agent
      - run:
          name: push to jfrog
          command: |
            export version=${CIRCLE_TAG:-$( [ "$CIRCLE_BRANCH" = "main" ] && echo "latest" || echo "prerelease" )}
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./target/x86_64-unknown-linux-musl/release/openbas-agent "https://filigran.jfrog.io/artifactory/openbas-agent/linux/x86_64/openbas-agent-$version"
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./installer/linux/agent-installer.sh "https://filigran.jfrog.io/artifactory/openbas-agent/linux/openbas-agent-installer-$version.sh"
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./installer/linux/agent-upgrade.sh "https://filigran.jfrog.io/artifactory/openbas-agent/linux/openbas-agent-upgrade-$version.sh"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  linux_arm_64_compile:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install curl musl-tools
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; rustup target add aarch64-unknown-linux-musl
      - run: . "$HOME/.cargo/env"; cargo build --target=aarch64-unknown-linux-musl --release
      - run: strip ./target/aarch64-unknown-linux-musl/release/openbas-agent
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  linux_arm_64_build:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install curl musl-tools
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; rustup target add aarch64-unknown-linux-musl
      - run: . "$HOME/.cargo/env"; cargo build --target=aarch64-unknown-linux-musl --release
      - run: strip ./target/aarch64-unknown-linux-musl/release/openbas-agent
      - run:
          name: push to jfrog
          command: |
            export version=${CIRCLE_TAG:-$( [ "$CIRCLE_BRANCH" = "main" ] && echo "latest" || echo "prerelease" )}
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./target/aarch64-unknown-linux-musl/release/openbas-agent "https://filigran.jfrog.io/artifactory/openbas-agent/linux/arm64/openbas-agent-$version"
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./installer/linux/agent-installer.sh "https://filigran.jfrog.io/artifactory/openbas-agent/linux/openbas-agent-installer-$version.sh"
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./installer/linux/agent-upgrade.sh "https://filigran.jfrog.io/artifactory/openbas-agent/linux/openbas-agent-upgrade-$version.sh"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  macos_arm_64_compile:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; cargo build --release
      - run: strip ./target/release/openbas-agent
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  macos_arm_64_build:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; cargo build --release
      - run: strip ./target/release/openbas-agent
      - run:
          name: push to jfrog
          command: |
            export version=${CIRCLE_TAG:-$( [ "$CIRCLE_BRANCH" = "main" ] && echo "latest" || echo "prerelease" )}
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./target/release/openbas-agent "https://filigran.jfrog.io/artifactory/openbas-agent/macos/arm64/openbas-agent-$version"
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./installer/macos/agent-installer.sh "https://filigran.jfrog.io/artifactory/openbas-agent/macos/openbas-agent-installer-$version.sh"
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./installer/macos/agent-upgrade.sh "https://filigran.jfrog.io/artifactory/openbas-agent/macos/openbas-agent-upgrade-$version.sh"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  macos_x86_64_compile:
    machine: true
    resource_class: openbas-platform/openbas-agent-macos-64bits-x86
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; cargo build --release
      - run: strip ./target/release/openbas-agent
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  macos_x86_64_build:
    machine: true
    resource_class: openbas-platform/openbas-agent-macos-64bits-x86
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; cargo build --release
      - run: strip ./target/release/openbas-agent
      - run:
          name: push to jfrog
          command: |
            export version=${CIRCLE_TAG:-$( [ "$CIRCLE_BRANCH" = "main" ] && echo "latest" || echo "prerelease" )}
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./target/release/openbas-agent "https://filigran.jfrog.io/artifactory/openbas-agent/macos/x86_64/openbas-agent-$version"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
workflows:
  openbas-agent:
    jobs:
      - windows_x86_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - windows_x86_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - linux_x86_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - linux_x86_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - linux_arm_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - linux_arm_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - macos_arm_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - macos_arm_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - macos_x86_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - /^release\/\d+\.\d+\.\d+$/
      - macos_x86_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - /^release\/\d+\.\d+\.\d+$/