debug=false

[openaev]
url = "http://localhost:3001"
token = "ChangeMe"
unsecured_certificate = false
with_proxy = false
installation_mode= "session-user"
service_name = "OAEVAgentService"
service_full_name = "OAEVAgentService"
tenant_id = "2cffad3a-0001-4078-b0e2-ef74274022c3"