debug=false

[openbas]
url = "http://localhost:3001"
token = "ChangeMe"
unsecured_certificate = false
with_proxy = false
installation_mode= "session-user"
service_name = "OBASAgentService"
service_full_name = "OBASAgentService"