name: Rust Build on Windows

on:
  push:
    branches:
      - cicd-test

jobs:
  poc_windows_x86_64_compile:
    name: poc_windows_x86_64_compile
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download rustup-init
      run: curl.exe --output rustup-init.exe --url https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe

    - name: Run rustup-init
      run: ./rustup-init.exe -vy

    - name: Install Rust Toolchain
      run: |
        rustup toolchain install stable-x86_64-pc-windows-msvc
        rustup default stable-x86_64-pc-windows-msvc

    - name: Uninstall Rust with Chocolatey
      run: |
        if command -v rustc > /dev/null; then
          rustc --version
          choco uninstall -y rust
        else
          echo "Rust is not installed."
        fi

    - name: Install MinGW and NSIS with Chocolatey
      run: choco install -y mingw nsis

    - name: Install Rust Quality Tools
      run: |
        rustup component add clippy
        rustup component add rustfmt
        cargo install cargo-audit

    - name: Cargo Check
      run: cargo check

    - name: Cargo Clippy
      run: cargo clippy -- -D warnings

    - name: Cargo Format Check
      run: cargo fmt -- --check

    - name: Cargo Audit
      run: cargo audit

    - name: Cargo Build
      run: cargo build --release

    - name: Cargo Test
      run: cargo test --release